# Generated by Django 5.2.7 on 2025-10-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('titulo_profesional', models.CharField(max_length=200)),
                ('especialidad', models.TextField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='profesionales/')),
                ('años_experiencia', models.IntegerField(blank=True, null=True)),
                ('calendly_username', models.CharField(max_length=100, unique=True)),
                ('tipo_servicio', models.CharField(choices=[('psicologia', 'Psicología'), ('metodologia', 'Metodología')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['orden', 'nombre_completo'],
            },
        ),
    ]
