# Generated by Django 5.2.7 on 2025-12-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_must_change',
            field=models.BooleanField(default=True),
        ),
    ]
