# Generated by Django 5.2.7 on 2025-11-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='servicio_interes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
