# Generated by Django 5.2.7 on 2025-12-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('servicio_interes', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Envío de Contacto',
                'verbose_name_plural': 'Envíos de Contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
