# Generated by Django 5.2.7 on 2025-11-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_userprofile'),
        ('services', '0003_contactsubmission_servicio_interes'),
    ]

    operations = [
    ]
